# Generated by Django 4.1.4 on 2023-05-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('updating_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=20, null=True)),
                ('ticker', models.CharField(max_length=5)),
                ('profile', models.TextField(blank=True, max_length=1000, null=True)),
                ('market_cap', models.FloatField(blank=True, max_length=30, null=True)),
                ('price_data', models.JSONField(blank=True, null=True)),
                ('avg_volume', models.CharField(blank=True, max_length=10, null=True)),
                ('one_month_volatility', models.FloatField(blank=True, null=True)),
                ('three_month_volatility', models.FloatField(blank=True, null=True)),
                ('six_month_volatility', models.FloatField(blank=True, null=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_stocks', to='updating_data.industry')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_stocks', to='updating_data.sector')),
                ('themes', models.ManyToManyField(blank=True, null=True, related_name='theme_stocks', to='updating_data.theme')),
            ],
        ),
    ]
