# Generated by Django 4.1.4 on 2023-05-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('price_data', models.JSONField(blank=True, null=True)),
                ('number_of_stocks', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('one_month_volatility', models.FloatField(blank=True, null=True)),
                ('three_month_volatility', models.FloatField(blank=True, null=True)),
                ('six_month_volatility', models.FloatField(blank=True, null=True)),
                ('themes', models.CharField(blank=True, max_length=200, null=True)),
                ('stocks', models.TextField(blank=True, max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('ticker', models.CharField(max_length=20, null=True)),
                ('price_data', models.JSONField(blank=True, null=True)),
                ('number_of_stocks', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('one_month_volatility', models.FloatField(blank=True, null=True)),
                ('three_month_volatility', models.FloatField(blank=True, null=True)),
                ('six_month_volatility', models.FloatField(blank=True, null=True)),
                ('industries', models.CharField(blank=True, max_length=200, null=True)),
                ('themes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('price_data', models.JSONField(blank=True, null=True)),
                ('number_of_stocks', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('one_month_volatility', models.FloatField(blank=True, null=True)),
                ('three_month_volatility', models.FloatField(blank=True, null=True)),
                ('six_month_volatility', models.FloatField(blank=True, null=True)),
                ('stocks', models.TextField(blank=True, max_length=250, null=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_themes', to='updating_data.industry')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_themes', to='updating_data.sector')),
            ],
        ),
        migrations.AddField(
            model_name='industry',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_industries', to='updating_data.sector'),
        ),
    ]
